//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int CodeReport { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateOfReport { get; set; }
        public Nullable<int> BadgeNum { get; set; }
        public Nullable<int> Id { get; set; }
        public Nullable<int> PriceFine { get; set; }
    
        public virtual Citizen Citizen { get; set; }
        public virtual Officer Officer { get; set; }
    }
}
