//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bgroup51_test2TraffixDBContext : DbContext
    {
        public bgroup51_test2TraffixDBContext()
            : base("name=bgroup51_test2TraffixDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Citizen> Citizens { get; set; }
        public virtual DbSet<Officer> Officers { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
    }
}
